# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  run-test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]   # Specify the runner environment

    runs-on: ${{ matrix.os }}  # Set the runner operating system
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install dependencies
        run: | 
          python -m pip install pytest       

      - name: Run Python Tests
        run: |
          pytest tests/unit

      - name: Upload Test Results
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: pytest-results.xml