# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest  # Specify the runner environment

    steps:
    - name: Install dependencies
      run: | 
        pip install pytest           

    - name: Run Python Tests
      run: |
        cd ..
        pytest tests/unit/BrowseRoleListings.py 

    - name: Upload Test Results
      uses: actions/upload-artifact@v2
      with:
        name: test-results
        path: pytest-results.xml
