# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  run-test:
    strategy:
      matrix:
        os: [ubuntu-latest]   # Specify the runner environment

    runs-on: ${{ matrix.os }}  # Set the runner operating system

    steps:     
      - name: Checkout
        uses: actions/checkout@v3      

      # Installing dependencies
      - name: Install pip (upgrade)
        run: python -m pip install -U pip
      
      - name: Install pytest
        run: pip install pytest
      
      - name: Install Selenium
        run: pip install selenium==3.141.0
      
      - name: Install WebDriverManager
        run: pip install webdriver_manager
      
      - name: Upgrade WebDriverManager
        run: pip install --upgrade webdriver_manager  

      - name: Run Python Tests
        run: |
          pytest tests/unit

      - name: Upload Screenshot 1
        uses: actions/upload-artifact@v2
        with:
          name: screenshot_1  # Name of the first artifact
          path: screenshot_1.png
        
      - name: Upload Screenshot 2
        uses: actions/upload-artifact@v2
        with:
          name: screenshot_2  # Name of the second artifact
          path: screenshot_2.png

      # - name: Upload Test Results
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: test-results
      #     path: pytest-results.xml
